encoding: UTF-8

title: Places to Work
description: Find places to work. Open and collaborative.
url: https://work.pqvst.com
repo: https://github.com/pqvst/places-to-work

exclude:
  - .git/
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
  - node_modules
  - scripts
  - package-lock.json
  - package.json
  - serve.sh

collections:
  cities:
    output: true

plugins: 
  - jekyll-redirect-from
