version: '3'

services:
  app:
    build: .
    environment:
      - VIRTUAL_HOST=cafeandcowork.com
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - NODE_ENV=production
    logging:
      options:
        max-file: "10"
        max-size: "10m"
    restart: always
 
networks:
  default:
    external:
      name: router_default